# Generated by Django 5.0.3 on 2025-01-05 13:25

import django.core.files.storage
import forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_pdf', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/local/Airbrokers_Admin_Chat_UI/media/output'), upload_to=forms.models.pdf_upload_to)),
                ('processed_pdf', models.FileField(blank=True, null=True, upload_to='output/')),
                ('form_data_json', models.FileField(blank=True, null=True, upload_to='output/')),
                ('normalized_data_json', models.FileField(blank=True, null=True, upload_to='output/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
