# Generated by Django 5.0.3 on 2025-01-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfupload',
            name='form_data_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdfupload',
            name='normalized_data_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
