# Generated by Django 5.0.3 on 2025-01-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_pdfupload_form_data_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfupload',
            name='form_data_json',
            field=models.FileField(blank=True, null=True, upload_to='output/'),
        ),
        migrations.AlterField(
            model_name='pdfupload',
            name='normalized_data_json',
            field=models.FileField(blank=True, null=True, upload_to='output/'),
        ),
    ]
